spring:
  application:
    name: spring-ai-converse-playground

  threads:
    virtual:
      enabled: true

management:
  info:
    build:
      enabled: true
    git:
      mode: FULL
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      access: read_only
    prometheus:
      access: read_only
    env:
      access: read_only
      show-values: ALWAYS
    configprops:
      access: read_only
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,prometheus,sbom

---

spring:
  config:
    activate:
      on-profile: elevenlabs

  elevenlabs:
    enabled: true
    api-key: ${ELEVENLABS_API_KEY:}
    defaults:
      voiceId: Xb7hH8MSUJpSbSDYk0k2

---

spring:
  config:
    activate:
      on-profile: dev

debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    me.pacphi: TRACE
    org.springframework: DEBUG
    com.fasterxml.jackson: TRACE