spring:
  application:
    name: spring-ai-converse-playground

  threads:
    virtual:
      enabled: true

management:
  info:
    build:
      enabled: true
    git:
      mode: FULL
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      access: read_only
    prometheus:
      access: read_only
    env:
      access: read_only
      show-values: ALWAYS
    configprops:
      access: read_only
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,prometheus,sbom

---

spring:
  config:
    activate:
      on-profile: assemblyai

  assemblyai:
    enabled: true
    api-key: ${ASSEMBLYAI_API_KEY:}

---

spring:
  config:
    activate:
      on-profile: elevenlabs

  elevenlabs:
    enabled: true
    api-key: ${ELEVENLABS_API_KEY:}
    defaults:
      voiceId: Xb7hH8MSUJpSbSDYk0k2

---

spring:
  config:
    activate:
      on-profile: google

  google:
    speech-to-text:
      enabled: true
      project: ${GOOGLE_PROJECT_ID:}
      defaults:
        language-code: ${GOOGLE_STT_LANGUAGE_CODE:en-US}
        model: ${GOOGLE_STT_MODEL:latest_long}
    text-to-speech:
      enabled: true
      defaults:
        language-code: ${GOOGLE_TTS_LANGUAGE_CODE:en-US}
        voice-gender: ${GOOGLE_TTS_VOICE_GENDER:NEUTRAL}
        audio-encoding: ${GOOGLE_TTS_AUDIO_ENCODING:MP3}

---

spring:
  config:
    activate:
      on-profile: picovoice

  picovoice:
    cheetah:
      enabled: true
      access-key: ${PICOVOICE_ACCESS_KEY:}
      defaults:
        model-path: ${PICOVOICE_MODEL_PATH:${user.dir}/target/classes/cheetah_params.pv}
        enable-automatic-punctuation: ${PICOVOICE_ENABLE_AUTO_PUNCTUATION:true}
    leopard:
      enabled: true
      access-key: ${PICOVOICE_ACCESS_KEY:}
      defaults:
        model-path: ${PICOVOICE_MODEL_PATH:${user.dir}/target/classes/leopard_params.pv}
        enable-automatic-punctuation: ${PICOVOICE_ENABLE_AUTO_PUNCTUATION:true}
        enable-diarization: ${PICOVOICE_ENABLE_DIARIZATION:true}
        verbose: ${PICOVOICE_VERBOSE:false}

---

spring:
  config:
    activate:
      on-profile: dev

debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    me.pacphi: TRACE
    org.springframework: DEBUG
    com.fasterxml.jackson: TRACE